# Generated by Django 3.1.3 on 2020-12-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='프로젝트명')),
                ('desc', models.TextField(verbose_name='설명')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('B', 'Basic'), ('I', 'Intermediate'), ('E', 'Expert')], default='B', max_length=50, verbose_name='기술명')),
                ('level', models.CharField(default='', max_length=50, verbose_name='수준')),
                ('percent', models.IntegerField(default=0, verbose_name='역량퍼센트')),
            ],
        ),
    ]
