# Generated by Django 3.1.3 on 2020-12-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('B', 'Basic'), ('I', 'Intermediate'), ('E', 'Expert')], default='B', max_length=50, verbose_name='수준'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='tag',
            field=models.CharField(default='', max_length=50, verbose_name='기술명'),
        ),
    ]
