# Generated by Django 3.1.3 on 2020-12-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20201208_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='SVG 아이콘파일'),
        ),
    ]
