# Generated by Django 3.1.3 on 2020-12-09 12:07

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_skill_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=data.models.skill_svg, verbose_name='SVG 아이콘파일'),
        ),
    ]
