# Generated by Django 3.1.3 on 2020-12-09 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20201209_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('DevOps', 'DevOps')], max_length=20, verbose_name='기술 구분')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.skilltype', verbose_name='기술구분'),
        ),
    ]
