# Generated by Django 3.1.3 on 2021-01-03 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20201210_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skill_used',
        ),
        migrations.AddField(
            model_name='project',
            name='all_skill_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.skill', verbose_name='사용기술'),
        ),
        migrations.AddField(
            model_name='project',
            name='main_skill_used',
            field=models.CharField(default='', max_length=50, verbose_name='주사용기술'),
        ),
    ]
