# Generated by Django 3.1.3 on 2021-01-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20210103_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='all_skill_used',
        ),
        migrations.AddField(
            model_name='project',
            name='sub_skill_used',
            field=models.ManyToManyField(related_name='sub_skill', to='data.Skill', verbose_name='보조사용기술'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='main_skill_used',
        ),
        migrations.AddField(
            model_name='project',
            name='main_skill_used',
            field=models.ManyToManyField(related_name='main_skill', to='data.Skill', verbose_name='주사용기술'),
        ),
    ]
