# Generated by Django 3.1.3 on 2021-01-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20210103_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('T', 'Tried'), ('F', 'Familiar')], default='T', max_length=50, verbose_name='수준'),
        ),
    ]
