# Generated by Django 3.1.3 on 2021-01-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20210104_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='term',
            field=models.CharField(default='', max_length=50, verbose_name='기간'),
        ),
    ]
