# Generated by Django 3.1.3 on 2021-01-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_project_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='', verbose_name='썸네일'),
        ),
    ]
