# Generated by Django 3.1.3 on 2021-02-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='깃헙주소'),
        ),
        migrations.AlterField(
            model_name='project',
            name='site',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='사이트주소'),
        ),
    ]
